=== UKGovernmentBEIS/heat-pump-options-service/hsm/configuration.service/Resources/hsm-inputs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://oxfordcc.co.uk/hsm-inputs"
	xmlns:hsm="http://oxfordcc.co.uk/hsm-inputs"
	elementFormDefault="qualified">

	<xs:element name="inputs" type="hsm:InputsType"></xs:element>

	<xs:complexType name="InputsType">
		<xs:annotation>
			<xs:documentation>Contains all elements required as inputs
			</xs:documentation>

		</xs:annotation>
		<xs:all>
			<xs:element name="house-type" type="hsm:HouseType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="wall-type" type="hsm:WallType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="house-age" type="hsm:HouseAgeType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="house-size-option1" type="hsm:HouseSizeOption1Type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="house-size-option2" type="hsm:HouseSizeOption2Type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="roof-type" type="hsm:RoofType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="glazing" type="hsm:GlazingType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="gas-supply" type="hsm:GasSupplyType" minOccurs="0" maxOccurs="1"/>
      <xs:element name="outside-space" type="hsm:OutsideSpace" minOccurs="0" maxOccurs="1"/>
			<xs:element name="current-heating-system" type="hsm:CurrentHeatingType" minOccurs="0" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>

	<!-- House Type -->
	<xs:complexType name="HouseType">
		<xs:annotation>
			<xs:documentation>
				Identified as a key factor in the type and size of heat pump required.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="answer" type="hsm:AnswerType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="explanation" type="hsm:ExplanationType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="question" type="hsm:QuestionType" use="required"/>
		<xs:attribute name="bctext" type="hsm:BCTextType" use="required"/>
		<xs:attribute name="optional" type="xs:boolean" use="required"/>
	</xs:complexType>

	<!-- Wall Type -->
	<xs:complexType name="WallType">
		<xs:annotation>
			<xs:documentation>
				Key factor in size of heat pump and other upgrade measures

				Suggested layer of decision tree
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="answer" type="hsm:AnswerType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="explanation" type="hsm:ExplanationType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="question" type="hsm:QuestionType" use="required"/>
		<xs:attribute name="bctext" type="hsm:BCTextType" use="required"/>
		<xs:attribute name="optional" type="xs:boolean" use="required"/>
	</xs:complexType>

	<!-- House Age -->
	<xs:complexType name="HouseAgeType">
		<xs:annotation>
			<xs:documentation>
				This question would be a proxy for wall type should the user not know
				that answer (type to be estimated from age)

				Question may be relevant in analysis

				Not a suggested layer of decision tree in its own right
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="answer" type="hsm:AnswerType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="explanation" type="hsm:ExplanationType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="question" type="hsm:QuestionType" use="required"/>
		<xs:attribute name="bctext" type="hsm:BCTextType" use="required"/>
		<xs:attribute name="optional" type="xs:boolean" use="required"/>
	</xs:complexType>

	<!-- House Size - Option 1 -->
	<xs:complexType name="HouseSizeOption1Type">
		<xs:annotation>
			<xs:documentation>
				Key factor in size of heat pump and other upgrade measures

				Suggested layer of decision tree
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="answer" type="hsm:AnswerType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="explanation" type="hsm:ExplanationType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="question" type="hsm:QuestionType" use="required"/>
		<xs:attribute name="bctext" type="hsm:BCTextType" use="required"/>
		<xs:attribute name="optional" type="xs:boolean" use="required"/>
	</xs:complexType>

	<!-- House Size - Option 2 -->
	<xs:complexType name="HouseSizeOption2Type">
		<xs:annotation>
			<xs:documentation>
				This question would be a proxy for floor area should the user not know
				that answer area to be estimated based on this answer

				Not a suggested layer of decision tree in its own right
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="answer" type="hsm:AnswerType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="explanation" type="hsm:ExplanationType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="question" type="hsm:QuestionType" use="required"/>
		<xs:attribute name="bctext" type="hsm:BCTextType" use="required"/>
		<xs:attribute name="optional" type="xs:boolean" use="required"/>
	</xs:complexType>

  <!-- Roof type -->
  <xs:complexType name="RoofType">
    <xs:annotation>
      <xs:documentation>
        This question will inform of home upgrade roof insulation requirements
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="answer" type="hsm:AnswerType" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="explanation" type="hsm:ExplanationType" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="question" type="hsm:QuestionType" use="required"/>
    <xs:attribute name="bctext" type="hsm:BCTextType" use="required"/>
    <xs:attribute name="optional" type="xs:boolean" use="required"/>
  </xs:complexType>

	<!-- Glazing -->
	<xs:complexType name="GlazingType">
		<xs:annotation>
			<xs:documentation>
				Question helps inform expected upgrades
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="answer" type="hsm:AnswerType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="explanation" type="hsm:ExplanationType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="question" type="hsm:QuestionType" use="required"/>
		<xs:attribute name="bctext" type="hsm:BCTextType" use="required"/>
		<xs:attribute name="optional" type="xs:boolean" use="required"/>
	</xs:complexType>

	<!-- Gas supply -->
	<xs:complexType name="GasSupplyType">
		<xs:annotation>
			<xs:documentation>
				Question informs whether a Hybrid HP is possible or not.  Removes
				options to be investigated through the decision tree
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="answer" type="hsm:AnswerType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="explanation" type="hsm:ExplanationType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="question" type="hsm:QuestionType" use="required"/>
		<xs:attribute name="bctext" type="hsm:BCTextType" use="required"/>
		<xs:attribute name="optional" type="xs:boolean" use="required"/>
	</xs:complexType>

  <xs:complexType name="OutsideSpace">
    <xs:annotation>
      <xs:documentation>
        This question is asked to ascertain whether sufficient outdoor area is available for a ground source heat pump installation.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="answer" type="hsm:AnswerType" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="explanation" type="hsm:ExplanationType" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="question" type="hsm:QuestionType" use="required"/>
    <xs:attribute name="bctext" type="hsm:BCTextType" use="required"/>
    <xs:attribute name="optional" type="xs:boolean" use="required"/>
  </xs:complexType>

	<!-- Current heating system -->
	<xs:complexType name="CurrentHeatingType">
		<xs:annotation>
			<xs:documentation>
        This question will inform the carbon savings attributed to a heat pump installation as a comparison with the current heating system.
      </xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="answer" type="hsm:AnswerType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="explanation" type="hsm:ExplanationType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="question" type="hsm:QuestionType" use="required"/>
		<xs:attribute name="bctext" type="hsm:BCTextType" use="required"/>
		<xs:attribute name="optional" type="xs:boolean" use="required"/>
	</xs:complexType>

	<xs:complexType name="AnswerType">
		<xs:sequence>
			<xs:element name="usertext" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="certificate-match" type="hsm:CertificateMatchType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="key" type="xs:string" use="required"/>
    <xs:attribute name="dbencoding" type="xs:short" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="CertificateMatchType">
		<xs:annotation>
			<xs:documentation>
				An element where the text is used to match with a value found in
				an EPC certificate, the key attribute identifies the value in
				the certificate and the match type describes which match
				algorithm to use.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="epc-text" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>

		<xs:attribute name="epc-key" type="xs:string" use="required"/>
		<xs:attribute name="match-type" type="hsm:EPCMatchType" use="required"/>
	</xs:complexType>
	
	<xs:simpleType name="QuestionType">
		<xs:restriction base="xs:string">
			<xs:minLength value="2"/>
			<xs:maxLength value="128"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="EPCMatchType">
		<xs:annotation>
			<xs:documentation>
				How answer choices are matched to values found in an energy performance certificate. 
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="exact"/>
			<xs:enumeration value="integer-in-range"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ExplanationType">
		<xs:restriction base="xs:string">
			<xs:minLength value="0"></xs:minLength>
			<xs:maxLength value="512"></xs:maxLength>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="BCTextType">
		<xs:annotation>
			<xs:documentation>
				This is a short text value to be used in the bread crumb text.  
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="2"/>
			<xs:maxLength value="26"/>
		</xs:restriction>
	</xs:simpleType>
	
	</xs:schema>

=== UKGovernmentBEIS/heat-pump-options-service/hsm/ui/wwwroot/data/questions.xml
<?xml version="1.0" encoding="UTF-8"?>
<hsm:inputs xmlns:hsm="http://oxfordcc.co.uk/hsm-inputs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://oxfordcc.co.uk/hsm-inputs hsm-inputs.xsd ">
  <hsm:house-type optional="true" question="What type of home do you have?" bctext="House Type">
    <hsm:answer key="detached" dbencoding="1">
      <hsm:usertext>Detached</hsm:usertext>
      <hsm:certificate-match epc-key="built-form" match-type="exact">
        <hsm:epc-text>Detached</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:certificate-match epc-key="property-type" match-type="exact">
        <hsm:epc-text>House</hsm:epc-text>
        <hsm:epc-text>Bungalow</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description>A house that is not joined to any other house.</hsm:description>
    </hsm:answer>
    <hsm:answer key="semidetached" dbencoding="2">
      <hsm:usertext>Semi-Detached</hsm:usertext>
      <hsm:certificate-match epc-key="built-form" match-type="exact">
        <hsm:epc-text>Semi-Detached</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:certificate-match epc-key="property-type" match-type="exact">
        <hsm:epc-text>House</hsm:epc-text>
        <hsm:epc-text>Bungalow</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description>A house that is joined to another house on one side by a shared wall.</hsm:description>
    </hsm:answer>
    <hsm:answer key="midterrace" dbencoding="3">
      <hsm:usertext>Mid-Terrace</hsm:usertext>
      <hsm:certificate-match epc-key="built-form" match-type="exact">
        <hsm:epc-text>Mid-Terrace</hsm:epc-text>
        <hsm:epc-text>Enclosed Mid-Terrace</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:certificate-match epc-key="property-type" match-type="exact">
        <hsm:epc-text>House</hsm:epc-text>
        <hsm:epc-text>Bungalow</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description>A house that is attached to other properties on both sides.</hsm:description>
    </hsm:answer>
    <hsm:answer key="flatapartment" dbencoding="4">
      <hsm:usertext>Flat / Apartment</hsm:usertext>
      <hsm:certificate-match epc-key="property-type" match-type="exact">
        <hsm:epc-text>Flat</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description>A self-contained housing unit that is part of a larger building, generally on a single storey.</hsm:description>
    </hsm:answer>
    <hsm:answer key="parkhome" dbencoding="5">
      <hsm:usertext>Park Home</hsm:usertext>
      <hsm:certificate-match epc-key="property-type" match-type="exact">
        <hsm:epc-text>Park Home</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description>A pre-fabricated mobile building occupied as a permanent home, located with others in a dedicated area of land.</hsm:description>
    </hsm:answer>
    <hsm:answer key="maisonette" dbencoding="4">
      <hsm:usertext>Maisonette</hsm:usertext>
      <hsm:certificate-match epc-key="property-type" match-type="exact">
	    <hsm:epc-text>Maisonette</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description>A self-contained housing unit that is part of a larger building, generally on two storeys.</hsm:description>
    </hsm:answer>
    <hsm:explanation>We are asking this question to allow us to provide more accurate information about your energy efficiency. For example, terraced houses lose less heat through their side walls.</hsm:explanation>
  </hsm:house-type>
  <hsm:wall-type optional="true" question="What is the main type of external wall construction in your home?" bctext="Wall Type">
    <hsm:answer key="soliduninsulated" dbencoding="1">
      <hsm:usertext>Solid - uninsulated</hsm:usertext>
      <hsm:certificate-match epc-key="walls-description" match-type="exact">
        <hsm:epc-text>Solid brick, as built, no insulation (assumed)</hsm:epc-text>
        <hsm:epc-text>Solid brick, as built, partial insulation (assumed)</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description>A single layer of solid brickwork, blockwork or stone, often with a plasterboard inner layer. With no insulation on the inside or outside.</hsm:description>
    </hsm:answer>
    <hsm:answer key="solidinsulated" dbencoding="2">
      <hsm:usertext>Solid - insulated</hsm:usertext>
      <hsm:certificate-match epc-key="walls-description" match-type="exact">
        <hsm:epc-text>Solid brick, with internal insulation</hsm:epc-text>
        <hsm:epc-text>Solid brick, as built, insulated (assumed)</hsm:epc-text>
        <hsm:epc-text>Solid brick, with external insulation</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description>A single layer of solid brickwork, blockwork or stone, often with a plasterboard inner layer. With insulation on either the inside or outside.</hsm:description>
    </hsm:answer>
    <hsm:answer key="cavityunfilled" dbencoding="3">
      <hsm:usertext>Cavity - unfilled</hsm:usertext>
      <hsm:certificate-match epc-key="walls-description" match-type="exact">
        <hsm:epc-text>Cavity wall, as built, no insulation (assumed)</hsm:epc-text>
        <hsm:epc-text>Cavity wall,</hsm:epc-text>
        <hsm:epc-text>Cavity wall, no insulation (assumed)</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description>Two layers of solid brickwork, blockwork or stone separated by a hollow centre (cavity) which has not been filled with insulation.</hsm:description>
    </hsm:answer>
    <hsm:answer key="cavityfilled" dbencoding="4">
      <hsm:usertext>Cavity - filled</hsm:usertext>
      <hsm:certificate-match epc-key="walls-description" match-type="exact">
        <hsm:epc-text>Cavity wall, as built, insulated (assumed)</hsm:epc-text>
        <hsm:epc-text>Cavity wall, filled cavity</hsm:epc-text>
        <hsm:epc-text>Cavity wall, filled cavity and external insulation</hsm:epc-text>
        <hsm:epc-text>Cavity wall, filled cavity and internal insulation</hsm:epc-text>
        <hsm:epc-text>Cavity wall, insulated (assumed)</hsm:epc-text>
        <hsm:epc-text>Cavity wall, partial insulation (assumed)</hsm:epc-text>
        <hsm:epc-text>Cavity wall, with external insulation</hsm:epc-text>
        <hsm:epc-text>Cavity wall, with internal insulation</hsm:epc-text>
        <hsm:epc-text>Cob, filled cavity</hsm:epc-text>
        <hsm:epc-text>Cob, filled cavity and internal insulation</hsm:epc-text>
        <hsm:epc-text>Granite or whin, filled cavity</hsm:epc-text>
        <hsm:epc-text>Granite or whinstone, filled cavity</hsm:epc-text>
        <hsm:epc-text>Sandstone, filled cavity</hsm:epc-text>
        <hsm:epc-text>Solid brick, filled cavity</hsm:epc-text>
        <hsm:epc-text>System built, filled cavity</hsm:epc-text>
        <hsm:epc-text>System built, filled cavity and external insulation</hsm:epc-text>
        <hsm:epc-text>System built, filled cavity and internal insulation</hsm:epc-text>
        <hsm:epc-text>Timber frame, filled cavity</hsm:epc-text>
        <hsm:epc-text>Timber frame, filled cavity and external insulation</hsm:epc-text>
        <hsm:epc-text>Timber frame, filled cavity and internal insulation</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description>Two layers of solid brickwork, blockwork or stone separated by a cavity which has been filled with insulation.</hsm:description>
    </hsm:answer>
    <hsm:answer key="dont-know" dbencoding="0">
      <hsm:usertext>Don't Know</hsm:usertext>
      <hsm:description/>
    </hsm:answer>
    <hsm:explanation>The type of walls that you have make a large difference to your energy efficiency and how much heating you require. 
			If your home has more than one external wall construction type, then please choose the majority. If you don’t know then we will estimate the external wall type based on the age of your home.
		</hsm:explanation>
  </hsm:wall-type>
  <hsm:house-age optional="true" question="Approximately when was your home built?" bctext="House Age">
    <hsm:answer key="pre-1900" dbencoding="1">
      <hsm:usertext>Before 1900</hsm:usertext>
      <hsm:certificate-match epc-key="construction-age-band" match-type="exact">
        <hsm:epc-text>England and Wales: before 1900</hsm:epc-text>
        <hsm:epc-text>1800</hsm:epc-text>
        <hsm:epc-text>1820</hsm:epc-text>
        <hsm:epc-text>1849</hsm:epc-text>
        <hsm:epc-text>1850</hsm:epc-text>
        <hsm:epc-text>1876</hsm:epc-text>
        <hsm:epc-text>1880</hsm:epc-text>
        <hsm:epc-text>1889</hsm:epc-text>
        <hsm:epc-text>1890</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description/>
    </hsm:answer>
    <hsm:answer key="1900-1929" dbencoding="2">
      <hsm:usertext>1900 – 1929</hsm:usertext>
      <hsm:certificate-match epc-key="construction-age-band" match-type="exact">
        <hsm:epc-text>England and Wales: 1900-1929</hsm:epc-text>
        <hsm:epc-text>1900</hsm:epc-text>
        <hsm:epc-text>1902</hsm:epc-text>
        <hsm:epc-text>1910</hsm:epc-text>
        <hsm:epc-text>1920</hsm:epc-text>
        <hsm:epc-text>1929</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description/>
    </hsm:answer>
    <hsm:answer key="1930-1949" dbencoding="3">
      <hsm:usertext>1930 – 1949</hsm:usertext>
      <hsm:certificate-match epc-key="construction-age-band" match-type="exact">
        <hsm:epc-text>England and Wales: 1930-1949</hsm:epc-text>
        <hsm:epc-text>1930</hsm:epc-text>
        <hsm:epc-text>1935</hsm:epc-text>
        <hsm:epc-text>1940</hsm:epc-text>
      </hsm:certificate-match>
      <hsm:description/>
    </hsm:answer>
    <hsm:answer key="1950-1966" dbencoding="4">
      <hsm:usertext>1950 – 1966</hsm:usertext>
      <hsm:certificate-match epc-key="construction-age-band" match-type="exact">
        <hsm:epc-text>England and Wales: 1950-1966</hsm:epc-text>
        <hsm:epc-text>1950</hsm:epc-text>
        <hsm:epc-text>1960</hsm:epc-text>
        <hsm:epc-text>1965</hsm:epc-text>
      </hsm:certificate-match>
